//
// This file was generated by the JPA Modeler
//
package ci.kossovo.ecole.entity;

import java.io.Serializable;

import javax.persistence.CascadeType;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.IdClass;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Version;

@Entity
@Table(name = "T_ETUDIANT_COURS")
@IdClass(EtudiantCoursID.class)
public class EtudiantCours implements Serializable {
	private static final long serialVersionUID = 1L;

	@Id
	private Long id_etudiant;
	@Id
    private Long id_cours;
	
	@Version
	private Long version;
    
	private boolean absence;

	private String motif;

	@ManyToOne(cascade=CascadeType.PERSIST)
	@JoinColumn(name = "id_cours", insertable = false, updatable = false)
	private Cours cours;

	@ManyToOne(cascade=CascadeType.PERSIST)
	@JoinColumn(name = "id_etudiant", insertable = false, updatable = false)
	private Etudiant etudiant;


	public EtudiantCours() {

	}

	
	public EtudiantCours(boolean absence, String motif) {
		super();
		this.absence = absence;
		this.motif = motif;
	}


	public EtudiantCours(Long id_etudiant, Long id_cours,  boolean absence, String motif) {
		super();
		this.id_etudiant = id_etudiant;
		this.id_cours = id_cours;
		this.absence = absence;
		this.motif = motif;
	}

	
	@Override
	public String toString() {
		return String.format("EtudiantCours[%s,%s,%s,%s]", id_cours,id_etudiant,absence, motif);
	}

	

	public boolean isAbsence() {
		return absence;
	}


	public void setAbsence(boolean absence) {
		this.absence = absence;
	}


	public String getMotif() {
		return this.motif;
	}

	public void setMotif(String motif) {
		this.motif = motif;
	}

	public Etudiant getEtudiant() {
		return this.etudiant;
	}

	public void setEtudiant(Etudiant etudiant) {
		this.etudiant = etudiant;
	}

	public Cours getCours() {
		return cours;
	}

	public void setCours(Cours cours) {
		this.cours = cours;
	}


	public Long getId_etudiant() {
		return id_etudiant;
	}


	public void setId_etudiant(Long id_etudiant) {
		this.id_etudiant = id_etudiant;
	}


	public Long getId_cours() {
		return id_cours;
	}


	public void setId_cours(Long id_cours) {
		this.id_cours = id_cours;
	}


	public Long getVersion() {
		return version;
	}


	public void setVersion(Long version) {
		this.version = version;
	}

	


	

}
