//
// This file was generated by the JPA Modeler
//
package ci.kossovo.ecole.entity;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

@Entity
@Table(name="T_PROMOTION")
public class Promotion extends AbstractEntity{
	private static final long serialVersionUID = 1L;


	// Promotion est lié à  filiere
    @ManyToOne(fetch= FetchType.LAZY)
    @JoinColumn(name="id_filiere")
    private Filiere filiere;
    
    // clé étrangère  
    @Column(name="id_filiere", insertable= false, updatable= false)
    private long idFiliere;

  
    private String libelle;

 
    private String description;


    public Promotion() {

    }

   
    

    public Promotion(Filiere filiere, long idFiliere, String libelle, String description) {
		super();
		this.filiere = filiere;
		this.idFiliere = idFiliere;
		this.libelle = libelle;
		this.description = description;
	}


    @Override
	public String toString() {
		return String.format("Promotion[%s,%s]", idFiliere,libelle);
	}

	public Filiere getFiliere() {
        return this.filiere;
    }

    public void setFiliere(Filiere filiere) {
        this.filiere = filiere;
    }

    public String getLibelle() {
        return this.libelle;
    }

    public void setLibelle(String libelle) {
        this.libelle = libelle;
    }

    public String getDescription() {
        return this.description;
    }

    public void setDescription(String description) {
        this.description = description;
    }



	public long getIdFiliere() {
		return idFiliere;
	}



	public void setIdFiliere(long idFiliere) {
		this.idFiliere = idFiliere;
	}



	
	

    
}
